name: flutter_mini_project
description: "Mini flutter project"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.0.0
  go_router: ^13.2.1
  flutter_bloc: ^8.1.4
  http: ^1.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  country_flags: ^2.2.0
  get_it: ^7.6.7
  equatable: ^2.0.5
  very_good_analysis: ^5.1.0

  path_provider: ^2.1.2
  hydrated_bloc: ^9.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
